# Site Settings
title: Josue Alfaro
tagline: Software Developer, Human Being
description: > #ingnore newlines until the next tag
    I am a Computer Engineer graduating from The University of Texas at Austin in May 2017.
email: josuealf59@gmail.com
timezone: America/Chicago
